version: '3'

services:
  nginx:
    image: drupal-nginx
    build: 
      context: ./docker/nginx
    volumes:
      - "./app:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on: 
      - app

  app:
    env_file: ./common.env
    image: drupal-app
    build: 
      context: ./docker/php
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    env_file: ./common.env
    image: mysql:5.6
    container_name: 'drupal-db'